### ISSUE TITLE
unneeded libs in libopkele.pc ?

### ISSUE THREAD

**Issue by nirik** [klevernothings/libopkele#2]
Greetings. I've submitted a review of libopkele for Fedora: 
https://bugzilla.redhat.com/show_bug.cgi?id=825333

In that review it was noticed that the libopkele.pc has: 
Libs: -L${libdir} -lopkele -lcurl   -lexpat -ltidy

but only actually ever uses curl includes... 

Should "-lexpat -ltidy" be removed there?

**Comment by hacker** [comment]
Err.. I'm not sure what you're talking about, the discovery uses both expat and tidy. If you're talking about the files not being used from installed headers, that means you may want to adjust packaging, which is not yet bundled with libopkele itself, so I can't really fixed it.

**Comment by nirik** [comment]
I think the reporter was just confused and I didn't check things out before reporting this. 

I think you can close this off. Sorry for the noise...

**Comment by hacker** [comment]
No problem, thanks for coming, anyway ;-)
