### ISSUE TITLE
Illegal header guards

### ISSUE THREAD

**Issue by jwakely** [klevernothings/libopkele#4]
The naming convention used for header guards in libopkele is forbidden by the C++ standard:

```
#ifndef __OPKELE_ITERATOR_H
```

Any name beginning with double underscores of an underscore followed by an uppercase letter is reserved to the implementation (meaning the compiler and standard library).

There is no reason not to use simply:

```
#ifndef OPKELE_ITERATOR_H
```

Using leading underscores for header guards is a terrible habit that serves no purpose and should never be used.

**Comment by hacker** [comment]
And thank you for reminding me that it's about time for me to quit programming, as I came to the place when it wasn't so badly ruled by patterns, standards and established practices and people were way more tolerant towards each other's habits and could adhere to the standards they like. Luckily, compilers still allow me this little eccentricity. Probably, not for a long now.
