### ISSUE TITLE
Invalid return type in basic_filterator

### ISSUE THREAD

**Issue by jwakely** [klevernothings/libopkele#5]
`basic_filterator::operator++(int)` returns by value, but `basic_filterator<TI>` is an abstract type because `basic_filterator<TI>::is_interesting()` is a pure virtual function, so you cannot return an object of an abstract type.

This is rejected by GCC 4.9

**Comment by hacker** [comment]
Thank you, somewhat embarrassing, as this function was there just for completeness, I simply removed it.
